# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: TayyabPC

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'sonarscanner'
    arguments: 'begin /o:"itayyab" /k:"dotnetcoresample" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(sonarlogin)" /d:sonar.exclusions="**/ClientApp/**" /d:sonar.scm.enabled=true /d:sonar.cs.vstest.reportsPaths="$(System.DefaultWorkingDirectory)\TestResults\*.trx" /d:sonar.cs.opencover.reportsPaths="$(System.DefaultWorkingDirectory)\TestResults\*.opencover.xml"'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"'
    modifyOutputPath: false
   
- task: PowerShell@2
  inputs:
    filePath: './MoveZip.ps1'
    arguments: '-ExecutionPolicy Bypass -source "$(System.DefaultWorkingDirectory)\DotnetCoreSample\bin\Release\netcoreapp3.1\publish.zip" -dest "$(build.artifactStagingDirectory)\WebApp.zip"'         
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'test'
    arguments: '-r TestResults --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover'
- task: PowerShell@2
  inputs:
    filePath: './MoveCoverageFile.ps1'
    arguments: '-ExecutionPolicy Bypass'        
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'sonarscanner'
    arguments: 'end /d:sonar.login="$(sonarlogin)"'
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'WebApp'
#     publishLocation: 'Container'    
    
# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Azure for Students (fb359318-74d9-4c9d-924a-e40b68321da1)'
#     appType: 'webAppLinux'
#     WebAppName: 'DotnetCoreSample20210723150916'
#     packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'